title: FinOps toolkit
description: A collection of customizable FinOps solutions that automate and extend native Microsoft Cloud capabilities.
remote_theme: just-the-docs/just-the-docs

# Markdown options -- https://jekyllrb.com/docs/configuration/markdown/
kramdown:
  # Kramdown options -- https://kramdown.gettalong.org/options.html
  parse_block_html: true

  # GFM options -- https://github.com/kramdown/parser-gfm
  gfm_emojis: true

url: https://microsoft.github.io/finops-toolkit

aux_links:
  FTK on GitHub: https://github.com/microsoft/finops-toolkit

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  highlight-green:
    color: green
  note:
    title: üö©i Note
    color: yellow
  tip:
    title: üí° Tip
    color: blue
  important:
    title: ‚ú® Important
    color: blue
  warning:
    title: ‚ö†Ô∏è Warning
    color: red
  new:
    title: üÜï New
    color: purple
