title: FinOps toolkit
description: A collection of customizable FinOps solutions that automate and extend native Microsoft Cloud capabilities.
remote_theme: just-the-docs/just-the-docs

url: https://microsoft.github.io/finops-toolkit

aux_links:
  FTK on GitHub: https://github.com/microsoft/finops-toolkit

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  custom:
    color: green
  note:
    title: ğŸš© Note
    color: yellow
  tipcallout:
    title: ğŸ’¡ Tip
    color: blue
  important:
    title: âœ¨ Important
    color: blue
  warning:
    title: âš ï¸ Warning
    color: red
  new:
    title: ğŸ†• New
    color: purple
