name: 'PowerShell Tests'

on: [pull_request]
jobs:
    run_pester_tests:
        name: Pester
        runs-on: Windows-latest
        steps:
        - uses: actions/checkout@v3
        - name: Run Meta Tests
          shell: pwsh
          run: ./src/scripts/Start-PesterTests.ps1 -Type 'Meta' -InstallPreReqs
        - uses: actions/checkout@v3
        - name: Run Unit Tests
          shell: pwsh
          run: ./src/scripts/Start-PesterTests.ps1 -Type 'Unit'
            